- name: update/clone repo - pull latest changes
  git:
    - repo: "{{ repo_git_url }}"
      dest: "{{ app_work_dir }}"
      update: yes
      version: master
      accept_hostkey: yes
  
  tags:
    code-deploy
  
